package application;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

public class MainSceneController {
	@FXML
	private TextField tftitle;
	
    @FXML
    private TextField bombsfield;

    @FXML
    private TextField flagsfield;

    @FXML
    private TextField timefield;


	// Event Listener on Button.onAction
	@FXML
	public void btnclicked(ActionEvent event) {
		// TODO Autogenerated
		//Stage mainWindow =  (Stage) tftitle.getScene().getWindow();
		//String title = tftitle.getText();
		//mainWindow.setTitle(title);
		bombsfield.setText("test");
	}
}
