package application;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.GridPane;
import javafx.scene.control.Control;
import javafx.scene.Node;

//import java.awt.event.MouseEvent;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.Random;
import java.util.Scanner;

import javafx.event.ActionEvent;

public class MainSceneController {
	
    private int difficulty = 1;
    private int bombcount = 9;
    private int timerseconds = 180;
    private boolean hyperbomb = false;
    private int[][] fieldVisible = new int[9][9];
    private int[][] fieldHidden = new int[9][9];
    private int arraydimension = 9;
    private int flagcnt = 0;
    private int i;
    private int j;
    private int m=0;
    private int cou;
    
    @FXML
    private Button button00;
    
    @FXML
    private Button button01;
    
    @FXML
    private Button button02;

    @FXML
    private Button button03;

    @FXML
    private Button button04;

    @FXML
    private Button button05;

    @FXML
    private Button button06;

    @FXML
    private Button button07;

    @FXML
    private Button button08;

    @FXML
    private Button button10;

    @FXML
    private Button button11;

    @FXML
    private Button button12;

    @FXML
    private Button button13;

    @FXML
    private Button button14;

    @FXML
    private Button button15;

    @FXML
    private Button button16;

    @FXML
    private Button button17;

    @FXML
    private Button button18;

    @FXML
    private Button button20;

    @FXML
    private Button button21;

    @FXML
    private Button button22;

    @FXML
    private Button button23;

    @FXML
    private Button button24;

    @FXML
    private Button button25;

    @FXML
    private Button button26;

    @FXML
    private Button button27;

    @FXML
    private Button button28;

    @FXML
    private Button button30;

    @FXML
    private Button button31;

    @FXML
    private Button button32;

    @FXML
    private Button button33;

    @FXML
    private Button button34;

    @FXML
    private Button button35;

    @FXML
    private Button button36;

    @FXML
    private Button button37;

    @FXML
    private Button button38;

    @FXML
    private Button button40;

    @FXML
    private Button button41;

    @FXML
    private Button button42;

    @FXML
    private Button button43;

    @FXML
    private Button button44;

    @FXML
    private Button button45;

    @FXML
    private Button button46;

    @FXML
    private Button button47;

    @FXML
    private Button button48;

    @FXML
    private Button button50;

    @FXML
    private Button button51;

    @FXML
    private Button button52;

    @FXML
    private Button button53;

    @FXML
    private Button button54;

    @FXML
    private Button button55;

    @FXML
    private Button button56;

    @FXML
    private Button button57;

    @FXML
    private Button button58;

    @FXML
    private Button button60;

    @FXML
    private Button button61;

    @FXML
    private Button button62;

    @FXML
    private Button button63;

    @FXML
    private Button button64;

    @FXML
    private Button button65;

    @FXML
    private Button button66;

    @FXML
    private Button button67;

    @FXML
    private Button button68;

    @FXML
    private Button button70;

    @FXML
    private Button button71;

    @FXML
    private Button button72;

    @FXML
    private Button button73;

    @FXML
    private Button button74;

    @FXML
    private Button button75;

    @FXML
    private Button button76;

    @FXML
    private Button button77;

    @FXML
    private Button button78;

    @FXML
    private Button button80;

    @FXML
    private Button button81;

    @FXML
    private Button button82;

    @FXML
    private Button button83;

    @FXML
    private Button button84;

    @FXML
    private Button button85;

    @FXML
    private Button button86;

    @FXML
    private Button button87;

    @FXML
    private Button button88;
    
    @FXML
    private GridPane GridPane;
    
	@FXML
	private TextField tftitle;
	
    @FXML
    private TextField bombsfield;

    @FXML
    private TextField flagsfield;

    @FXML
    private TextField timefield;

    
	// Event Listener on Button.onAction
	@FXML
	public void btnclicked(ActionEvent event) {
		// TODO Autogenerated
		//Stage mainWindow =  (Stage) tftitle.getScene().getWindow();
		//String title = tftitle.getText();
		//mainWindow.setTitle(title);
		bombsfield.setText("test");
		System.out.println("Hello");
		//GridPane[0][0].setText("trol");
		//System.out.println(board[0][0]);
	}
	
	@FXML
    void startgame(ActionEvent event) {
		
    }
	
	
	//public Button[][] board = {{button00, button01, button02, button03, button04, button05, button06, button07, button08}};
	
    @FXML
    void mouseEntered(MouseEvent e) {
    	 Button[][] board = {{button00, button01, button02, button03, button04, button05, button06, button07, button08},
    			 {button10, button11, button12, button13, button14, button15, button16, button17, button18},
    			 {button20, button21, button22, button23, button24, button25, button26, button27, button28},
    			 {button30, button31, button32, button33, button34, button35, button36, button37, button38},
    			 {button40, button41, button42, button43, button44, button45, button46, button47, button48},
    			 {button50, button51, button52, button53, button54, button55, button56, button57, button58},
    			 {button60, button61, button62, button63, button64, button65, button66, button67, button68},
    			 {button70, button71, button72, button73, button74, button75, button76, button77, button78},
    			 {button80, button81, button82, button83, button84, button85, button86, button87, button88}};
    	//button00.setText("troll");
    	//Button[][] board = {{button00, button01, button02, button03, button04, button05, button06, button07, button08}};
    	String check = (((Control) e.getSource()).getId());
    	System.out.println(check);
    	char x = (check.charAt(6));
    	char y = (check.charAt(7));
    	i = Character.getNumericValue(x);
    	j = Character.getNumericValue(y);
    	//System.out.println(i+","+j);
    	//System.out.println(board[i][j]);
    	//if (cou!=1) 
    	System.out.println(i+","+j);
    	//System.out.println(board[i][j]);
    	if (cou!=1) startGame(); 
    	cou = 1;
    	boolean flag = playMove();
        if (flag) displayVisible();
        
        if(checkWin())
        {
            displayHidden();
            System.out.println("\n================You WON!!!================");
            //break;
        }
    	//System.out.println(i+","+j);
    	//System.out.println(board[i][j]);
    	//board[i][j].setText("hi");
    	//board[x][y].setStyle("-fx-background-color: #ff0000; ");
    	//board[x][y].setStyle("-fx-text-fill: #ff0000");
    	//board[i][j].setDisable(true);
    	//board[i][j].setStyle("-fx-opacity: 1;"+
    	//"-fx-text-fill: #ff0000;"+
    	//"-fx-background-color: #ffffff;");
    	//board[x][y].setStyle("-fx-text-fill: #ff0000");
    	System.out.println(i+","+j);
    	//displayVisible();
    	//Node source = (Node)e.getSource() ;
        //int colIndex = GridPane.getColumnIndex((Node) e.getTarget());
        //flagsfield.setText(""+colIndex);
        //int rowIndex = GridPane.getRowIndex((Node) e.getTarget());
        //System.out.println("Mouse entered cell "+ colIndex+ rowIndex);
    }
	
	 public void displayVisible()
	    {   
		 Button[][] board = {{button00, button01, button02, button03, button04, button05, button06, button07, button08},
    			 {button10, button11, button12, button13, button14, button15, button16, button17, button18},
    			 {button20, button21, button22, button23, button24, button25, button26, button27, button28},
    			 {button30, button31, button32, button33, button34, button35, button36, button37, button38},
    			 {button40, button41, button42, button43, button44, button45, button46, button47, button48},
    			 {button50, button51, button52, button53, button54, button55, button56, button57, button58},
    			 {button60, button61, button62, button63, button64, button65, button66, button67, button68},
    			 {button70, button71, button72, button73, button74, button75, button76, button77, button78},
    			 {button80, button81, button82, button83, button84, button85, button86, button87, button88}};
		    System.out.println(i+","+j);
	    	//System.out.println(board[i][j]);
//		    board[i][j+2].setStyle("-fx-opacity: 1;"+
//		        	"-fx-text-fill: #ff0000;"+
//		        	"-fx-background-color: #ffffff;");
		    System.out.print("\t ");
	        for(int i=0; i<arraydimension; i++)
	        {
	            System.out.print(" " + i + "  ");
	        }
	        System.out.print("\n");
	        for(int i=0; i<arraydimension; i++)
	        {
	            System.out.print(i + "\t| ");
	            for(int j=0; j<arraydimension; j++)
	            {
	                if(fieldVisible[i][j]==0)
	                {
	                    System.out.print("?");
	                    
	                }
	                else if(fieldVisible[i][j]==50)
	                {
	                    System.out.print(" ");
	                    board[i][j].setDisable(true);
	                    board[i][j].setStyle("-fx-opacity: 1;"+
	                	"-fx-text-fill: #ff0000;"+
	                	"-fx-background-color: #ffffff;");
	                }
	                else if(fieldVisible[i][j]==20) {
	                	System.out.print("F");
	                }
	                else if(fieldVisible[i][j]==100)
	                {
	                    System.out.print("X");
	                    board[i][j].setDisable(true);
	                    board[i][j].setText("X");
	                    board[i][j].setStyle("-fx-opacity: 1;"+
	    	                	"-fx-text-fill: #ff0000;"+
	    	                	"-fx-background-color: #ffffff;");
	                    
	                }
	                else if(fieldVisible[i][j]==200)
	                {
	                    System.out.print("B");
	                    board[i][j].setDisable(true);
	                    board[i][j].setText("B");
	                    board[i][j].setStyle("-fx-opacity: 1;"+
	    	                	"-fx-text-fill: #ff0000;"+
	    	                	"-fx-background-color: #ffffff;");
	                }
	                else
	                {
	                    System.out.print(fieldVisible[i][j]);
	                    board[i][j].setDisable(true);
	                    board[i][j].setText(""+fieldVisible[i][j]);
	                    board[i][j].setStyle("-fx-opacity: 1;"+
	    	                	"-fx-text-fill: #ff0000;"+
	    	                	"-fx-background-color: #ffffff;");
	                }
	                System.out.print(" | ");
	            }
	            System.out.print("\n");
	        }
	    }

	    public void displayHidden()
	    {   
	    	Button[][] board = {{button00, button01, button02, button03, button04, button05, button06, button07, button08},
	    			 {button10, button11, button12, button13, button14, button15, button16, button17, button18},
	    			 {button20, button21, button22, button23, button24, button25, button26, button27, button28},
	    			 {button30, button31, button32, button33, button34, button35, button36, button37, button38},
	    			 {button40, button41, button42, button43, button44, button45, button46, button47, button48},
	    			 {button50, button51, button52, button53, button54, button55, button56, button57, button58},
	    			 {button60, button61, button62, button63, button64, button65, button66, button67, button68},
	    			 {button70, button71, button72, button73, button74, button75, button76, button77, button78},
	    			 {button80, button81, button82, button83, button84, button85, button86, button87, button88}};
	        System.out.print("\t ");
	        for(int i=0; i<arraydimension; i++)
	        {
	            System.out.print(" " + i + "  ");
	        }
	        System.out.print("\n");
	        for(int i=0; i<arraydimension; i++)
	        {
	            System.out.print(i + "\t| ");
	            for(int j=0; j<arraydimension; j++)
	            {
	                if(fieldHidden[i][j]==0)
	                {
	                    System.out.print(" ");
	                    board[i][j].setDisable(true);
	                    board[i][j].setStyle("-fx-opacity: 1;"+
	    	                	"-fx-text-fill: #ff0000;"+
	    	                	"-fx-background-color: #ffffff;");
	                }
	                else if(fieldHidden[i][j]==100)
	                {
	                    System.out.print("X");
	                    board[i][j].setDisable(true);
	                    board[i][j].setText("X");
	                    board[i][j].setStyle("-fx-opacity: 1;"+
	    	                	"-fx-text-fill: #ff0000;"+
	    	                	"-fx-background-color: #ffffff;");
	                }
	                else if(fieldHidden[i][j]==200)
	                {
	                    System.out.print("B");
	                    board[i][j].setDisable(true);
	                    board[i][j].setText("B");
	                    board[i][j].setStyle("-fx-opacity: 1;"+
	    	                	"-fx-text-fill: #ff0000;"+
	    	                	"-fx-background-color: #ffffff;");
	                }
	                else
	                {
	                    System.out.print(fieldHidden[i][j]);
	                    board[i][j].setDisable(true);
	                    board[i][j].setText(""+fieldVisible[i][j]);
	                    board[i][j].setStyle("-fx-opacity: 1;"+
	    	                	"-fx-text-fill: #ff0000;"+
	    	                	"-fx-background-color: #ffffff;");
	                }
	                System.out.print(" | ");
	            }
	            System.out.print("\n");
	        }
	    }

	    public void fixVisible(int i, int j)
	    {   if (fieldVisible[i][j] == 0 || fieldVisible[i][j]==20) {
	        fieldVisible[i][j] = 50;
	        if(i!=0)
	        {   
	        	if (fieldVisible[i-1][j] == 0 || fieldVisible[i-1][j] == 20) {
	            fieldVisible[i-1][j] = fieldHidden[i-1][j];
	            if(fieldVisible[i-1][j]==0 || fieldVisible[i-1][j] == 20) fixVisible(i-1,j);
	            	//fieldVisible[i-1][j] = 50;
	        	}
	            if(j!=0)
	            {
	            	if (fieldVisible[i-1][j-1] == 0 || fieldVisible[i-1][j-1] == 20) {
	                fieldVisible[i-1][j-1] = fieldHidden[i-1][j-1];
	                if(fieldVisible[i-1][j-1]==0 || fieldVisible[i-1][j-1] == 20) fixVisible(i-1,j-1);
	                	//fieldVisible[i-1][j-1]=50;
	            	}
	            }
	        }
	        if(i!=(arraydimension-1))
	        {
	        	if (fieldVisible[i+1][j] == 0 || fieldVisible[i+1][j] == 20) {
	            fieldVisible[i+1][j]=fieldHidden[i+1][j];
	            if(fieldVisible[i+1][j]==0 || fieldVisible[i+1][j]==20) fixVisible(i+1,j); 
	            	//fieldVisible[i+1][j]=50;
	        	}
	            if(j!=(arraydimension-1))
	            {
	            	if (fieldVisible[i+1][j+1] == 0 || fieldVisible[i+1][j+1] == 20) {
	                fieldVisible[i+1][j+1]= fieldHidden[i+1][j+1];
	                if(fieldVisible[i+1][j+1]==0 || fieldVisible[i+1][j+1] == 20) fixVisible(i+1,j+1);
	                //fieldVisible[i+1][j+1] = 50;
	            	}
	            }
	        }
	        if(j!=0)
	        {   
	        	if (fieldVisible[i][j-1] == 0 || fieldVisible[i][j-1] == 20) {
	            fieldVisible[i][j-1]=fieldHidden[i][j-1];
	            if(fieldVisible[i][j-1]==0 || fieldVisible[i][j-1] == 20) fixVisible(i,j-1);
	            //fieldVisible[i][j-1] = 50;
	        	}
	            if(i!=(arraydimension-1))
	            {
	            	if (fieldVisible[i+1][j-1]==0 || fieldVisible[i+1][j-1] == 20) {
	                fieldVisible[i+1][j-1]=fieldHidden[i+1][j-1];
	                if(fieldVisible[i+1][j-1]==0 || fieldVisible[i+1][j-1] == 20) fixVisible(i+1,j-1);
	                //fieldVisible[i+1][j-1] = 50;
	            	}
	            }
	        }
	        if(j!=(arraydimension-1))
	        {
	        	if (fieldVisible[i][j+1] == 0 || fieldVisible[i][j+1] == 20) {
	            fieldVisible[i][j+1]=fieldHidden[i][j+1];
	            if(fieldVisible[i][j+1]==0 || fieldVisible[i][j+1] == 20) fixVisible(i, j+1);
	            //fieldVisible[i][j+1] = 50;
	        	}
	            if(i!=0)
	            {
	            	if (fieldVisible[i-1][j+1] == 0 || fieldVisible[i-1][j+1] == 20) {
	                fieldVisible[i-1][j+1]=fieldHidden[i-1][j+1];
	                if(fieldVisible[i-1][j+1]==0 || fieldVisible[i-1][j+1] == 20) fixVisible(i-1,j+1);
	                //fieldVisible[i-1][j+1] = 50;
	            	}
	            }
	        }
	    }
	    }

	    public void fixNeighbours(int i, int j)
	    {
	        fieldVisible[i][j] = fieldHidden[i][j];
	    }

	    public boolean playMove()
	    {
//	        Scanner sc= new Scanner(System.in);
//	        System.out.print("\nEnter action(0 for left click 1 for right click flag):");
//	        int m=sc.nextInt();
//	        System.out.print("Enter Row Number: ");
//	        int i= sc.nextInt();
//	        System.out.print("Enter Column Number: ");
//	        int j= sc.nextInt();

	        if(i<0 || i>(arraydimension-1) || j<0 || j>(arraydimension-1) || (fieldVisible[i][j]!=0 && fieldVisible[i][j]!=20) ||( m!=0 && m!=1))
	        {
	            System.out.print("\nIncorrect Input!!");
	            return true;
	        }
	        
	        if (m==0) {
	      /*	if (fieldVisible[i][j]==20) {
	        	System.out.print("\nIncorrect Input!!");
	        	return true;
	        }*/
	        if(fieldHidden[i][j]==100 || fieldHidden[i][j]==200)
	        {
	            displayHidden();
	            System.out.print("Oops! You stepped on a mine!\n============GAME OVER============");
	            return false;
	        }
	        else if(fieldHidden[i][j]==0)
	        {
	            fixVisible(i, j);
	        }
	        else
	        {
	            fixNeighbours(i, j);
	        }
	        }
	        else {
	        	if (fieldVisible[i][j]==0) {
	        		flagcnt++;
	        	    fieldVisible[i][j] = 20;
	        	    if (fieldHidden[i][j] == 200 && flagcnt <= 4) {
	        	    	for (int k=0; k<arraydimension; k++) {
	        	    		fieldVisible[i][k] = fieldHidden[i][k];
	        	    				if (fieldVisible[i][k]==0) fieldVisible[i][k]=50;
	        	    	}
	        	    	for (int u=0; u<arraydimension; u++) {
	        	    		fieldVisible[u][j] = fieldHidden[u][j];
	        	    		if (fieldVisible[u][j]==0) fieldVisible[u][j]=50;
	        	    	}
	        	    }
	        	}  	
	        	else if (fieldVisible[i][j]==20)
	        		fieldVisible[i][j] = 0;
	        }

	        return true;
	    }

	    public void buildHidden()
	    {
	        for(int i=0; i<arraydimension; i++)
	        {
	            for(int j=0; j<arraydimension; j++)
	            {
	                int cnt=0;
	                if(fieldHidden[i][j]!=100 && fieldHidden[i][j]!=200)
	                {

	                    if(i!=0)
	                    {
	                        if(fieldHidden[i-1][j]==100 || fieldHidden[i-1][j]==200) cnt++;
	                        if(j!=0)
	                        {
	                            if(fieldHidden[i-1][j-1]==100 || fieldHidden[i-1][j-1]==200) cnt++;
	                        }

	                    }
	                    if(i!=(arraydimension-1))
	                    {
	                        if(fieldHidden[i+1][j]==100 || fieldHidden[i+1][j]==200) cnt++;
	                        if(j!=(arraydimension-1))
	                        {
	                            if(fieldHidden[i+1][j+1]==100 || fieldHidden[i+1][j+1]==200) cnt++;
	                        }
	                    }
	                    if(j!=0)
	                    {
	                        if(fieldHidden[i][j-1]==100 || fieldHidden[i][j-1]==200) cnt++;
	                        if(i!=(arraydimension-1))
	                        {
	                            if(fieldHidden[i+1][j-1]==100 || fieldHidden[i+1][j-1]==200) cnt++;
	                        }
	                    }
	                    if(j!=(arraydimension-1))
	                    {
	                        if(fieldHidden[i][j+1]==100 || fieldHidden[i][j+1]==200) cnt++;
	                        if(i!=0)
	                        {
	                            if(fieldHidden[i-1][j+1]==100 || fieldHidden[i-1][j+1]==200) cnt++;
	                        }
	                    }

	                    fieldHidden[i][j] = cnt;
	                }
	            }
	        }

	        //displayHidden();
	    }

	    public void setupField(int diff)
	    {
	        int var=0;
	        String data="";
	        while(var!=bombcount)
	        {
	            Random random = new Random();
	            int i = random.nextInt(arraydimension);
	            int j = random.nextInt(arraydimension);
	            //System.out.println("i: " + i + " j: " + j);
	            if (var==(bombcount-1) && hyperbomb) {
	            	fieldHidden[i][j] = 200;
	            	data = data + i+","+j+","+1+"\n";
	            }
	            else {
	            fieldHidden[i][j] = 100;
					data = data + i+","+j+","+0+"\n";
	            }
					//System.out.println(data);
	            var++;
	        }
	        try {
	        FileOutputStream file = new FileOutputStream("output.txt");			// Creates a FileOutputStream
			BufferedOutputStream output = new BufferedOutputStream(file);		// Creates a BufferedOutputStream
			
			byte[] array = data.getBytes();
			output.write(array);												// Writes data to the output stream
			
			output.close();
		     }
		    catch (Exception ex) {
			     ex.getStackTrace();
		      }
	             buildHidden();
	    }

	    public boolean checkWin()
	    {
	        for(int i=0; i<arraydimension; i++)
	        {
	            for(int j=0; j<arraydimension; j++)
	            {
	                if(fieldVisible[i][j]==0)
	                {
	                    if(fieldHidden[i][j]!=100 && fieldHidden[i][j]!=200)
	                    {
	                        return false;
	                    }
	                }
	            }
	        }
	        return true;
	    }

	    public void startGame()
	    {
	        System.out.println("\n\n================Welcome to Minesweeper ! ================\n");
	        setupField(1);
	        boolean timerstart = true;
	        //CountTimer timer = new CountTimer(timerseconds);

	        boolean flag = true;
	        //while(flag)
	        //{
	            displayVisible();
	            //flag = playMove();
	            //displayVisible();
	            //if (timerstart) timer.starttimer();
	            timerstart = false;
	            //timer.printtimer();
//	            if (timer.checktimerend()) {
//	            	displayHidden();
//	            	System.out.println("\n-------Time out! You LOST!-------");
//	            	break;
//	            }
//	            if(checkWin())
//	            {
//	                displayHidden();
//	                System.out.println("\n================You WON!!!================");
//	                //break;
//	            }
	        }
	   // }
}
